-- Generated by tools/generate.cjs. Edit model.cjs / constraints.sql, then regenerate.
BEGIN;

CREATE TABLE "accounts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "email_normalized" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "auth_version" integer NOT NULL DEFAULT 1,
  "deletion_requested_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("email_normalized"),
  CONSTRAINT "accounts_check_0" CHECK (status IN ('active','restricted','deleting','deleted'))
);

CREATE TABLE "principals" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "kind" text NOT NULL,
  "account_id" uuid,
  "claimed_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "principals_check_0" CHECK (kind IN ('guest','account')),
  CONSTRAINT "principals_check_1" CHECK (kind <> 'account' OR account_id IS NOT NULL)
);

CREATE TABLE "guest_credentials" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "principal_id" uuid NOT NULL,
  "secret_hash" text NOT NULL,
  "revoked_at" timestamptz,
  "last_used_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  UNIQUE ("secret_hash")
);

CREATE TABLE "sessions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "refresh_hash" text NOT NULL,
  "family_id" uuid NOT NULL,
  "replaced_by_id" uuid,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  "platform" text NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("refresh_hash")
);

CREATE TABLE "email_challenges" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "email_normalized" text NOT NULL,
  "purpose" text NOT NULL,
  "code_hmac" text NOT NULL,
  "attempts" integer NOT NULL DEFAULT 0,
  "expires_at" timestamptz NOT NULL,
  "consumed_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "email_challenges_check_0" CHECK (purpose IN ('login','register','delete_account')),
  CONSTRAINT "email_challenges_check_1" CHECK (attempts >= 0)
);

CREATE TABLE "regions" (
  "code" text NOT NULL,
  "parent_code" text,
  "level" text NOT NULL,
  "name_ja" text NOT NULL,
  "name_zh" text NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("code"),
  CONSTRAINT "regions_check_0" CHECK (level IN ('prefecture','municipality'))
);

CREATE TABLE "interests" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "code" text NOT NULL,
  "name_zh" text NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "sort_order" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  UNIQUE ("code")
);

CREATE TABLE "media_assets" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "owner_principal_id" uuid NOT NULL,
  "purpose" text NOT NULL,
  "object_key" text NOT NULL,
  "status" text NOT NULL DEFAULT 'initiated',
  "mime" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "width" integer,
  "height" integer,
  "checksum" text,
  "upload_expires_at" timestamptz NOT NULL,
  "cleanup_after" timestamptz,
  "deleted_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("object_key"),
  CONSTRAINT "media_assets_check_0" CHECK (purpose IN ('board','profile','dating','event')),
  CONSTRAINT "media_assets_check_1" CHECK (status IN ('initiated','uploaded','processing','approved','rejected','deleting','deleted')),
  CONSTRAINT "media_assets_check_2" CHECK (size_bytes > 0 AND size_bytes <= 5000000),
  CONSTRAINT "media_assets_check_3" CHECK (mime IN ('image/jpeg','image/png','image/webp')),
  CONSTRAINT "media_assets_check_4" CHECK ((width IS NULL AND height IS NULL) OR (width > 0 AND height > 0 AND width::bigint * height <= 20000000))
);

CREATE TABLE "profiles" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "nickname" text NOT NULL,
  "bio" text NOT NULL DEFAULT '',
  "avatar_media_id" uuid,
  "region_code" text,
  "visibility" text NOT NULL DEFAULT 'public',
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("account_id"),
  UNIQUE ("avatar_media_id"),
  CONSTRAINT "profiles_check_0" CHECK (visibility IN ('public','hidden'))
);

CREATE TABLE "account_settings" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "allow_stranger_dm" boolean NOT NULL DEFAULT true,
  "push_enabled" boolean NOT NULL DEFAULT true,
  "lockscreen_preview" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  UNIQUE ("account_id")
);

CREATE TABLE "profile_interests" (
  "account_id" uuid NOT NULL,
  "interest_id" uuid NOT NULL,
  PRIMARY KEY ("account_id","interest_id")
);

CREATE TABLE "push_devices" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "installation_id" uuid NOT NULL,
  "token_ciphertext" text NOT NULL,
  "token_hash" text NOT NULL,
  "platform" text NOT NULL,
  "revoked_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("installation_id"),
  UNIQUE ("token_hash"),
  CONSTRAINT "push_devices_check_0" CHECK (platform IN ('ios','android'))
);

CREATE TABLE "consent_records" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "terms_version" text NOT NULL,
  "privacy_version" text NOT NULL,
  "accepted_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "posts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "author_principal_id" uuid NOT NULL,
  "display_mode" text NOT NULL DEFAULT 'guest',
  "scope" text NOT NULL DEFAULT 'public',
  "category" text NOT NULL DEFAULT 'general',
  "title" text NOT NULL,
  "body" text NOT NULL,
  "region_code" text,
  "status" text NOT NULL DEFAULT 'pending',
  "published_at" timestamptz,
  "expires_at" timestamptz,
  "deleted_at" timestamptz,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  CONSTRAINT "posts_check_0" CHECK (status IN ('pending','visible','rejected','hidden','deleted','expired')),
  CONSTRAINT "posts_check_1" CHECK (published_at IS NULL OR expires_at > published_at),
  CONSTRAINT "posts_check_2" CHECK (status <> 'visible' OR (published_at IS NOT NULL AND expires_at IS NOT NULL)),
  CONSTRAINT "posts_check_3" CHECK (display_mode IN ('guest','account')),
  CONSTRAINT "posts_check_4" CHECK (scope IN ('public','dating')),
  CONSTRAINT "posts_check_5" CHECK (category IN ('interest','city','general'))
);

CREATE TABLE "comments" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "post_id" uuid NOT NULL,
  "author_principal_id" uuid NOT NULL,
  "display_mode" text NOT NULL DEFAULT 'guest',
  "reply_to_id" uuid,
  "body" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'pending',
  "published_at" timestamptz,
  "expires_at" timestamptz,
  "deleted_at" timestamptz,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("post_id","id"),
  CONSTRAINT "comments_check_0" CHECK (status IN ('pending','visible','rejected','hidden','deleted','expired')),
  CONSTRAINT "comments_check_1" CHECK (published_at IS NULL OR expires_at > published_at),
  CONSTRAINT "comments_check_2" CHECK (status <> 'visible' OR (published_at IS NOT NULL AND expires_at IS NOT NULL)),
  CONSTRAINT "comments_check_3" CHECK (display_mode IN ('guest','account')),
  CONSTRAINT "comments_check_4" CHECK (reply_to_id IS NULL OR reply_to_id <> id)
);

CREATE TABLE "post_interests" (
  "post_id" uuid NOT NULL,
  "interest_id" uuid NOT NULL,
  PRIMARY KEY ("post_id","interest_id")
);

CREATE TABLE "post_media" (
  "post_id" uuid NOT NULL,
  "media_id" uuid NOT NULL,
  "position" integer NOT NULL,
  PRIMARY KEY ("post_id","media_id"),
  UNIQUE ("media_id"),
  UNIQUE ("post_id","position"),
  CONSTRAINT "post_media_check_0" CHECK (position >= 0 AND position < 9)
);

CREATE TABLE "comment_media" (
  "comment_id" uuid NOT NULL,
  "media_id" uuid NOT NULL,
  "position" integer NOT NULL,
  PRIMARY KEY ("comment_id","media_id"),
  UNIQUE ("media_id"),
  UNIQUE ("comment_id","position"),
  CONSTRAINT "comment_media_check_0" CHECK (position >= 0 AND position < 3)
);

CREATE TABLE "media_variants" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "media_id" uuid NOT NULL,
  "kind" text NOT NULL,
  "object_key" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "width" integer NOT NULL,
  "height" integer NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("media_id","kind"),
  UNIQUE ("object_key"),
  CONSTRAINT "media_variants_check_0" CHECK (kind IN ('display','thumbnail')),
  CONSTRAINT "media_variants_check_1" CHECK (size_bytes > 0),
  CONSTRAINT "media_variants_check_2" CHECK (width > 0 AND height > 0 AND GREATEST(width,height) <= 1920)
);

CREATE TABLE "groups" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "creator_id" uuid NOT NULL,
  "owner_id" uuid NOT NULL,
  "type" text NOT NULL DEFAULT 'ordinary',
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "rules" text NOT NULL DEFAULT '',
  "region_code" text,
  "interest_id" uuid,
  "status" text NOT NULL DEFAULT 'active',
  "capacity" integer DEFAULT 100,
  "active_count" integer NOT NULL DEFAULT 0,
  "version" integer NOT NULL DEFAULT 1,
  "dissolved_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "groups_check_0" CHECK (type IN ('ordinary','event','dating')),
  CONSTRAINT "groups_check_1" CHECK (status IN ('active','readonly','closed')),
  CONSTRAINT "groups_check_2" CHECK (active_count >= 0 AND (capacity IS NULL OR capacity >= active_count)),
  CONSTRAINT "groups_check_3" CHECK (type <> 'ordinary' OR (capacity IS NOT NULL AND capacity > 0)),
  CONSTRAINT "groups_check_4" CHECK (dissolved_at IS NULL OR status <> 'active')
);

CREATE TABLE "group_members" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "group_id" uuid NOT NULL,
  "account_id" uuid NOT NULL,
  "role" text NOT NULL DEFAULT 'member',
  "status" text NOT NULL DEFAULT 'active',
  "muted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  UNIQUE ("group_id","account_id"),
  CONSTRAINT "group_members_check_0" CHECK (role IN ('owner','member')),
  CONSTRAINT "group_members_check_1" CHECK (status IN ('active','left','banned'))
);

CREATE TABLE "membership_periods" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "group_member_id" uuid NOT NULL,
  "start_sequence" bigint NOT NULL,
  "end_sequence" bigint,
  "joined_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "left_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "membership_periods_check_0" CHECK (start_sequence >= 0),
  CONSTRAINT "membership_periods_check_1" CHECK (end_sequence IS NULL OR end_sequence >= start_sequence),
  CONSTRAINT "membership_periods_check_2" CHECK ((end_sequence IS NULL) = (left_at IS NULL))
);

CREATE TABLE "matches" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_low_id" uuid NOT NULL,
  "account_high_id" uuid NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "matched_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ended_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("account_low_id","account_high_id"),
  CONSTRAINT "matches_check_0" CHECK (account_low_id < account_high_id),
  CONSTRAINT "matches_check_1" CHECK (status IN ('active','ended'))
);

CREATE TABLE "conversations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "type" text NOT NULL,
  "group_id" uuid,
  "match_id" uuid,
  "account_low_id" uuid,
  "account_high_id" uuid,
  "status" text NOT NULL DEFAULT 'active',
  "last_sequence" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id"),
  UNIQUE ("group_id"),
  UNIQUE ("match_id"),
  UNIQUE ("type","account_low_id","account_high_id"),
  CONSTRAINT "conversations_check_0" CHECK (type IN ('group','direct','dating')),
  CONSTRAINT "conversations_check_1" CHECK (status IN ('active','readonly','closed')),
  CONSTRAINT "conversations_check_2" CHECK (last_sequence >= 0),
  CONSTRAINT "conversations_check_3" CHECK ((type='group' AND group_id IS NOT NULL AND match_id IS NULL AND account_low_id IS NULL AND account_high_id IS NULL) OR (type='direct' AND group_id IS NULL AND match_id IS NULL AND account_low_id < account_high_id) OR (type='dating' AND group_id IS NULL AND match_id IS NOT NULL AND account_low_id < account_high_id)),
  CONSTRAINT "conversations_check_4" CHECK (type='group' OR (account_low_id IS NOT NULL AND account_high_id IS NOT NULL))
);

CREATE TABLE "conversation_participants" (
  "conversation_id" uuid NOT NULL,
  "account_id" uuid NOT NULL,
  "muted" boolean NOT NULL DEFAULT false,
  "archived_at" timestamptz,
  PRIMARY KEY ("conversation_id","account_id")
);

CREATE TABLE "messages" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "conversation_id" uuid NOT NULL,
  "sender_id" uuid NOT NULL,
  "client_message_id" uuid NOT NULL,
  "sequence" bigint NOT NULL,
  "body" text NOT NULL,
  "status" text NOT NULL DEFAULT 'visible',
  "sent_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("sender_id","client_message_id"),
  UNIQUE ("conversation_id","sequence"),
  CONSTRAINT "messages_check_0" CHECK (status IN ('visible','deleted','expired')),
  CONSTRAINT "messages_check_1" CHECK (sequence > 0),
  CONSTRAINT "messages_check_2" CHECK (expires_at > sent_at)
);

CREATE TABLE "read_cursors" (
  "conversation_id" uuid NOT NULL,
  "account_id" uuid NOT NULL,
  "last_read_sequence" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("conversation_id","account_id"),
  CONSTRAINT "read_cursors_check_0" CHECK (last_read_sequence >= 0)
);

CREATE TABLE "message_request_receipts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "sender_id" uuid NOT NULL,
  "client_message_id" uuid NOT NULL,
  "conversation_id" uuid NOT NULL,
  "request_hash" text NOT NULL,
  "message_id" uuid,
  "sequence" bigint NOT NULL,
  "result_state" text NOT NULL DEFAULT 'saved',
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("sender_id","client_message_id"),
  CONSTRAINT "message_request_receipts_check_0" CHECK (result_state IN ('saved','expired'))
);

CREATE TABLE "age_declarations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "status" text NOT NULL DEFAULT 'self_declared',
  "statement_version" text NOT NULL,
  "declared_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "withdrawn_at" timestamptz,
  "expires_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("account_id"),
  CONSTRAINT "age_declarations_check_0" CHECK (status IN ('self_declared','withdrawn')),
  CONSTRAINT "age_declarations_check_1" CHECK ((status='self_declared' AND withdrawn_at IS NULL AND expires_at IS NULL) OR (status='withdrawn' AND withdrawn_at IS NOT NULL AND expires_at IS NOT NULL))
);

CREATE TABLE "dating_profiles" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "enabled" boolean NOT NULL DEFAULT false,
  "intro" text NOT NULL DEFAULT '',
  "region_code" text,
  "preferences" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" text NOT NULL DEFAULT 'pending',
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("account_id"),
  CONSTRAINT "dating_profiles_check_0" CHECK (status IN ('pending','visible','rejected','hidden'))
);

CREATE TABLE "dating_profile_interests" (
  "account_id" uuid NOT NULL,
  "interest_id" uuid NOT NULL,
  PRIMARY KEY ("account_id","interest_id")
);

CREATE TABLE "dating_photos" (
  "account_id" uuid NOT NULL,
  "media_id" uuid NOT NULL,
  "position" integer NOT NULL,
  PRIMARY KEY ("account_id","media_id"),
  UNIQUE ("media_id"),
  UNIQUE ("account_id","position"),
  CONSTRAINT "dating_photos_check_0" CHECK (position >= 0 AND position < 6)
);

CREATE TABLE "likes" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "from_account_id" uuid NOT NULL,
  "to_account_id" uuid NOT NULL,
  "decision" text NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("from_account_id","to_account_id"),
  CONSTRAINT "likes_check_0" CHECK (from_account_id <> to_account_id),
  CONSTRAINT "likes_check_1" CHECK (decision IN ('like','skip'))
);

CREATE TABLE "events" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "creator_id" uuid NOT NULL,
  "group_id" uuid,
  "cover_media_id" uuid,
  "title" text NOT NULL,
  "description" text NOT NULL,
  "region_code" text NOT NULL,
  "starts_at" timestamptz NOT NULL,
  "ends_at" timestamptz NOT NULL,
  "registration_deadline" timestamptz NOT NULL,
  "capacity" integer NOT NULL,
  "confirmed_count" integer NOT NULL DEFAULT 0,
  "status" text NOT NULL DEFAULT 'draft',
  "cancellation_policy" text NOT NULL,
  "cancel_reason" text,
  "cancelled_at" timestamptz,
  "actual_ended_at" timestamptz,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("group_id"),
  UNIQUE ("cover_media_id"),
  CONSTRAINT "events_check_0" CHECK (capacity > 0 AND confirmed_count >= 0 AND confirmed_count <= capacity),
  CONSTRAINT "events_check_1" CHECK (registration_deadline <= starts_at AND starts_at < ends_at),
  CONSTRAINT "events_check_2" CHECK (status IN ('draft','pending','open','ended','cancelled','hidden')),
  CONSTRAINT "events_check_3" CHECK (status <> 'cancelled' OR (cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL))
);

CREATE TABLE "event_private_details" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "event_id" uuid NOT NULL,
  "meeting_instructions" text NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("event_id")
);

CREATE TABLE "event_interests" (
  "event_id" uuid NOT NULL,
  "interest_id" uuid NOT NULL,
  PRIMARY KEY ("event_id","interest_id")
);

CREATE TABLE "event_registrations" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "event_id" uuid NOT NULL,
  "account_id" uuid NOT NULL,
  "status" text NOT NULL DEFAULT 'confirmed',
  "accepted_event_version" integer NOT NULL,
  "registered_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "cancelled_at" timestamptz,
  "left_at" timestamptz,
  "expires_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("event_id","account_id"),
  CONSTRAINT "event_registrations_check_0" CHECK (status IN ('confirmed','cancelled','left'))
);

CREATE TABLE "event_revisions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "event_id" uuid NOT NULL,
  "version" integer NOT NULL,
  "changed_fields" jsonb NOT NULL,
  "reason" text NOT NULL,
  "actor_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("event_id","version")
);

CREATE TABLE "blocks" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "blocker_id" uuid NOT NULL,
  "blocked_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("blocker_id","blocked_id"),
  CONSTRAINT "blocks_check_0" CHECK (blocker_id <> blocked_id)
);

CREATE TABLE "admin_accounts" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "login_name" text NOT NULL,
  "password_hash" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active',
  "role" text NOT NULL,
  "mfa_secret_ciphertext" text NOT NULL,
  "auth_version" integer NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  UNIQUE ("login_name"),
  CONSTRAINT "admin_accounts_check_0" CHECK (status IN ('active','disabled')),
  CONSTRAINT "admin_accounts_check_1" CHECK (role IN ('reviewer','operator','auditor'))
);

CREATE TABLE "admin_sessions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "admin_id" uuid NOT NULL,
  "token_hash" text NOT NULL,
  "mfa_verified_at" timestamptz NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "revoked_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("token_hash")
);

CREATE TABLE "reports" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "reporter_principal_id" uuid NOT NULL,
  "target_type" text NOT NULL,
  "post_id" uuid,
  "comment_id" uuid,
  "message_id" uuid,
  "account_id" uuid,
  "group_id" uuid,
  "event_id" uuid,
  "reason_code" text NOT NULL,
  "detail" text NOT NULL DEFAULT '',
  "status" text NOT NULL DEFAULT 'open',
  "resolved_at" timestamptz,
  "expires_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "reports_check_0" CHECK (num_nonnulls(post_id,comment_id,message_id,account_id,group_id,event_id)=1 AND ((target_type='post' AND post_id IS NOT NULL) OR (target_type='comment' AND comment_id IS NOT NULL) OR (target_type='message' AND message_id IS NOT NULL) OR (target_type='account' AND account_id IS NOT NULL) OR (target_type='group' AND group_id IS NOT NULL) OR (target_type='event' AND event_id IS NOT NULL))),
  CONSTRAINT "reports_check_1" CHECK (status IN ('open','reviewing','resolved'))
);

CREATE TABLE "moderation_actions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "report_id" uuid,
  "admin_id" uuid NOT NULL,
  "target_type" text NOT NULL,
  "post_id" uuid,
  "comment_id" uuid,
  "message_id" uuid,
  "account_id" uuid,
  "group_id" uuid,
  "event_id" uuid,
  "action" text NOT NULL,
  "reason" text NOT NULL,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "moderation_actions_check_0" CHECK (num_nonnulls(post_id,comment_id,message_id,account_id,group_id,event_id)=1 AND ((target_type='post' AND post_id IS NOT NULL) OR (target_type='comment' AND comment_id IS NOT NULL) OR (target_type='message' AND message_id IS NOT NULL) OR (target_type='account' AND account_id IS NOT NULL) OR (target_type='group' AND group_id IS NOT NULL) OR (target_type='event' AND event_id IS NOT NULL)))
);

CREATE TABLE "notifications" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_id" uuid NOT NULL,
  "type" text NOT NULL,
  "target_type" text NOT NULL,
  "target_id" uuid NOT NULL,
  "params" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "read_at" timestamptz,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "outbox" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "event_type" text NOT NULL,
  "aggregate_type" text NOT NULL,
  "aggregate_id" uuid NOT NULL,
  "payload" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "status" text NOT NULL DEFAULT 'pending',
  "attempts" integer NOT NULL DEFAULT 0,
  "available_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lease_until" timestamptz,
  "last_error_code" text,
  "dedupe_key" text NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("dedupe_key"),
  CONSTRAINT "outbox_check_0" CHECK (status IN ('pending','processing','succeeded','dead')),
  CONSTRAINT "outbox_check_1" CHECK (attempts >= 0)
);

CREATE TABLE "processed_events" (
  "consumer" text NOT NULL,
  "event_key" text NOT NULL,
  "processed_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("consumer","event_key")
);

CREATE TABLE "idempotency_records" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "actor_key" text NOT NULL,
  "method" text NOT NULL,
  "route_key" text NOT NULL,
  "key" text NOT NULL,
  "request_hash" text NOT NULL,
  "status" text NOT NULL,
  "resource_type" text,
  "resource_id" uuid,
  "response_code" integer,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("actor_key","method","route_key","key"),
  CONSTRAINT "idempotency_records_check_0" CHECK (status IN ('pending','completed'))
);

CREATE TABLE "deletion_jobs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "target_type" text NOT NULL,
  "target_id" uuid NOT NULL,
  "reason" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "requested_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completed_at" timestamptz,
  "retry_after" timestamptz,
  "dedupe_key" text NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("dedupe_key"),
  CONSTRAINT "deletion_jobs_check_0" CHECK (status IN ('pending','processing','completed','failed'))
);

CREATE TABLE "deletion_ledger" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "target_type" text NOT NULL,
  "target_id" uuid NOT NULL,
  "deleted_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "purge_reason" text NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("target_type","target_id")
);

CREATE TABLE "moderation_revisions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "target_type" text NOT NULL,
  "target_id" uuid NOT NULL,
  "version" integer NOT NULL,
  "fields" jsonb NOT NULL,
  "expires_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  UNIQUE ("target_type","target_id","version")
);

CREATE TABLE "direct_contact_states" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "account_low_id" uuid NOT NULL,
  "account_high_id" uuid NOT NULL,
  "low_sent_count" integer NOT NULL DEFAULT 0,
  "high_sent_count" integer NOT NULL DEFAULT 0,
  "low_first_sent_at" timestamptz,
  "high_first_sent_at" timestamptz,
  "low_first_replied_at" timestamptz,
  "high_first_replied_at" timestamptz,
  PRIMARY KEY ("id"),
  UNIQUE ("account_low_id","account_high_id"),
  CONSTRAINT "direct_contact_states_check_0" CHECK (account_low_id < account_high_id),
  CONSTRAINT "direct_contact_states_check_1" CHECK (low_sent_count >= 0 AND high_sent_count >= 0)
);

CREATE TABLE "daily_usage" (
  "account_id" uuid NOT NULL,
  "day_jst" date NOT NULL,
  "kind" text NOT NULL,
  "used_count" integer NOT NULL DEFAULT 0,
  PRIMARY KEY ("account_id","day_jst","kind"),
  CONSTRAINT "daily_usage_check_0" CHECK (kind IN ('new_dm_target','group_create')),
  CONSTRAINT "daily_usage_check_1" CHECK (used_count >= 0)
);

CREATE TABLE "group_owner_transfers" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "group_id" uuid NOT NULL,
  "from_account_id" uuid NOT NULL,
  "to_account_id" uuid NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "accepted_at" timestamptz,
  PRIMARY KEY ("id"),
  CONSTRAINT "group_owner_transfers_check_0" CHECK (status IN ('pending','accepted','cancelled')),
  CONSTRAINT "group_owner_transfers_check_1" CHECK (from_account_id <> to_account_id),
  CONSTRAINT "group_owner_transfers_check_2" CHECK (status <> 'accepted' OR accepted_at IS NOT NULL)
);

CREATE TABLE "policy_configs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "key" text NOT NULL,
  "value" jsonb NOT NULL,
  "version" integer NOT NULL DEFAULT 1,
  "updated_by_admin_id" uuid,
  PRIMARY KEY ("id"),
  UNIQUE ("key"),
  CONSTRAINT "policy_configs_check_0" CHECK (version > 0)
);
ALTER TABLE "principals" ADD CONSTRAINT "principals_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "principals_account_id_idx" ON "principals"("account_id");
ALTER TABLE "guest_credentials" ADD CONSTRAINT "guest_credentials_principal_id_fkey" FOREIGN KEY ("principal_id") REFERENCES "principals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "guest_credentials_principal_id_idx" ON "guest_credentials"("principal_id");
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "sessions_account_id_idx" ON "sessions"("account_id");
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_replaced_by_id_fkey" FOREIGN KEY ("replaced_by_id") REFERENCES "sessions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "sessions_replaced_by_id_idx" ON "sessions"("replaced_by_id");
ALTER TABLE "regions" ADD CONSTRAINT "regions_parent_code_fkey" FOREIGN KEY ("parent_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "regions_parent_code_idx" ON "regions"("parent_code");
ALTER TABLE "media_assets" ADD CONSTRAINT "media_assets_owner_principal_id_fkey" FOREIGN KEY ("owner_principal_id") REFERENCES "principals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "media_assets_owner_principal_id_idx" ON "media_assets"("owner_principal_id");
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "profiles_account_id_idx" ON "profiles"("account_id");
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_avatar_media_id_fkey" FOREIGN KEY ("avatar_media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "profiles_avatar_media_id_idx" ON "profiles"("avatar_media_id");
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_region_code_fkey" FOREIGN KEY ("region_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "profiles_region_code_idx" ON "profiles"("region_code");
ALTER TABLE "account_settings" ADD CONSTRAINT "account_settings_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "account_settings_account_id_idx" ON "account_settings"("account_id");
ALTER TABLE "profile_interests" ADD CONSTRAINT "profile_interests_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "profile_interests_account_id_idx" ON "profile_interests"("account_id");
ALTER TABLE "profile_interests" ADD CONSTRAINT "profile_interests_interest_id_fkey" FOREIGN KEY ("interest_id") REFERENCES "interests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "profile_interests_interest_id_idx" ON "profile_interests"("interest_id");
ALTER TABLE "push_devices" ADD CONSTRAINT "push_devices_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "push_devices_account_id_idx" ON "push_devices"("account_id");
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "consent_records_account_id_idx" ON "consent_records"("account_id");
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_principal_id_fkey" FOREIGN KEY ("author_principal_id") REFERENCES "principals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "posts_author_principal_id_idx" ON "posts"("author_principal_id");
ALTER TABLE "posts" ADD CONSTRAINT "posts_region_code_fkey" FOREIGN KEY ("region_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "posts_region_code_idx" ON "posts"("region_code");
ALTER TABLE "comments" ADD CONSTRAINT "comments_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "comments_post_id_idx" ON "comments"("post_id");
ALTER TABLE "comments" ADD CONSTRAINT "comments_author_principal_id_fkey" FOREIGN KEY ("author_principal_id") REFERENCES "principals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "comments_author_principal_id_idx" ON "comments"("author_principal_id");
ALTER TABLE "comments" ADD CONSTRAINT "comments_reply_to_id_fkey" FOREIGN KEY ("reply_to_id") REFERENCES "comments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "comments_reply_to_id_idx" ON "comments"("reply_to_id");
ALTER TABLE "post_interests" ADD CONSTRAINT "post_interests_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "post_interests_post_id_idx" ON "post_interests"("post_id");
ALTER TABLE "post_interests" ADD CONSTRAINT "post_interests_interest_id_fkey" FOREIGN KEY ("interest_id") REFERENCES "interests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "post_interests_interest_id_idx" ON "post_interests"("interest_id");
ALTER TABLE "post_media" ADD CONSTRAINT "post_media_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "post_media_post_id_idx" ON "post_media"("post_id");
ALTER TABLE "post_media" ADD CONSTRAINT "post_media_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "post_media_media_id_idx" ON "post_media"("media_id");
ALTER TABLE "comment_media" ADD CONSTRAINT "comment_media_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "comment_media_comment_id_idx" ON "comment_media"("comment_id");
ALTER TABLE "comment_media" ADD CONSTRAINT "comment_media_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "comment_media_media_id_idx" ON "comment_media"("media_id");
ALTER TABLE "media_variants" ADD CONSTRAINT "media_variants_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "media_variants_media_id_idx" ON "media_variants"("media_id");
ALTER TABLE "groups" ADD CONSTRAINT "groups_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "groups_creator_id_idx" ON "groups"("creator_id");
ALTER TABLE "groups" ADD CONSTRAINT "groups_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "groups_owner_id_idx" ON "groups"("owner_id");
ALTER TABLE "groups" ADD CONSTRAINT "groups_region_code_fkey" FOREIGN KEY ("region_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "groups_region_code_idx" ON "groups"("region_code");
ALTER TABLE "groups" ADD CONSTRAINT "groups_interest_id_fkey" FOREIGN KEY ("interest_id") REFERENCES "interests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "groups_interest_id_idx" ON "groups"("interest_id");
ALTER TABLE "group_members" ADD CONSTRAINT "group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "group_members_group_id_idx" ON "group_members"("group_id");
ALTER TABLE "group_members" ADD CONSTRAINT "group_members_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "group_members_account_id_idx" ON "group_members"("account_id");
ALTER TABLE "membership_periods" ADD CONSTRAINT "membership_periods_group_member_id_fkey" FOREIGN KEY ("group_member_id") REFERENCES "group_members"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "membership_periods_group_member_id_idx" ON "membership_periods"("group_member_id");
ALTER TABLE "matches" ADD CONSTRAINT "matches_account_low_id_fkey" FOREIGN KEY ("account_low_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "matches_account_low_id_idx" ON "matches"("account_low_id");
ALTER TABLE "matches" ADD CONSTRAINT "matches_account_high_id_fkey" FOREIGN KEY ("account_high_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "matches_account_high_id_idx" ON "matches"("account_high_id");
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversations_group_id_idx" ON "conversations"("group_id");
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "matches"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversations_match_id_idx" ON "conversations"("match_id");
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_account_low_id_fkey" FOREIGN KEY ("account_low_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversations_account_low_id_idx" ON "conversations"("account_low_id");
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_account_high_id_fkey" FOREIGN KEY ("account_high_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversations_account_high_id_idx" ON "conversations"("account_high_id");
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversation_participants_conversation_id_idx" ON "conversation_participants"("conversation_id");
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "conversation_participants_account_id_idx" ON "conversation_participants"("account_id");
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "messages_conversation_id_idx" ON "messages"("conversation_id");
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "messages_sender_id_idx" ON "messages"("sender_id");
ALTER TABLE "read_cursors" ADD CONSTRAINT "read_cursors_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "read_cursors_conversation_id_idx" ON "read_cursors"("conversation_id");
ALTER TABLE "read_cursors" ADD CONSTRAINT "read_cursors_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "read_cursors_account_id_idx" ON "read_cursors"("account_id");
ALTER TABLE "message_request_receipts" ADD CONSTRAINT "message_request_receipts_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "message_request_receipts_sender_id_idx" ON "message_request_receipts"("sender_id");
ALTER TABLE "message_request_receipts" ADD CONSTRAINT "message_request_receipts_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "message_request_receipts_conversation_id_idx" ON "message_request_receipts"("conversation_id");
ALTER TABLE "message_request_receipts" ADD CONSTRAINT "message_request_receipts_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "message_request_receipts_message_id_idx" ON "message_request_receipts"("message_id");
ALTER TABLE "age_declarations" ADD CONSTRAINT "age_declarations_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "age_declarations_account_id_idx" ON "age_declarations"("account_id");
ALTER TABLE "dating_profiles" ADD CONSTRAINT "dating_profiles_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_profiles_account_id_idx" ON "dating_profiles"("account_id");
ALTER TABLE "dating_profiles" ADD CONSTRAINT "dating_profiles_region_code_fkey" FOREIGN KEY ("region_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_profiles_region_code_idx" ON "dating_profiles"("region_code");
ALTER TABLE "dating_profile_interests" ADD CONSTRAINT "dating_profile_interests_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "dating_profiles"("account_id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_profile_interests_account_id_idx" ON "dating_profile_interests"("account_id");
ALTER TABLE "dating_profile_interests" ADD CONSTRAINT "dating_profile_interests_interest_id_fkey" FOREIGN KEY ("interest_id") REFERENCES "interests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_profile_interests_interest_id_idx" ON "dating_profile_interests"("interest_id");
ALTER TABLE "dating_photos" ADD CONSTRAINT "dating_photos_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "dating_profiles"("account_id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_photos_account_id_idx" ON "dating_photos"("account_id");
ALTER TABLE "dating_photos" ADD CONSTRAINT "dating_photos_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "dating_photos_media_id_idx" ON "dating_photos"("media_id");
ALTER TABLE "likes" ADD CONSTRAINT "likes_from_account_id_fkey" FOREIGN KEY ("from_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "likes_from_account_id_idx" ON "likes"("from_account_id");
ALTER TABLE "likes" ADD CONSTRAINT "likes_to_account_id_fkey" FOREIGN KEY ("to_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "likes_to_account_id_idx" ON "likes"("to_account_id");
ALTER TABLE "events" ADD CONSTRAINT "events_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "events_creator_id_idx" ON "events"("creator_id");
ALTER TABLE "events" ADD CONSTRAINT "events_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "events_group_id_idx" ON "events"("group_id");
ALTER TABLE "events" ADD CONSTRAINT "events_cover_media_id_fkey" FOREIGN KEY ("cover_media_id") REFERENCES "media_assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "events_cover_media_id_idx" ON "events"("cover_media_id");
ALTER TABLE "events" ADD CONSTRAINT "events_region_code_fkey" FOREIGN KEY ("region_code") REFERENCES "regions"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "events_region_code_idx" ON "events"("region_code");
ALTER TABLE "event_private_details" ADD CONSTRAINT "event_private_details_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_private_details_event_id_idx" ON "event_private_details"("event_id");
ALTER TABLE "event_interests" ADD CONSTRAINT "event_interests_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_interests_event_id_idx" ON "event_interests"("event_id");
ALTER TABLE "event_interests" ADD CONSTRAINT "event_interests_interest_id_fkey" FOREIGN KEY ("interest_id") REFERENCES "interests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_interests_interest_id_idx" ON "event_interests"("interest_id");
ALTER TABLE "event_registrations" ADD CONSTRAINT "event_registrations_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_registrations_event_id_idx" ON "event_registrations"("event_id");
ALTER TABLE "event_registrations" ADD CONSTRAINT "event_registrations_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_registrations_account_id_idx" ON "event_registrations"("account_id");
ALTER TABLE "event_revisions" ADD CONSTRAINT "event_revisions_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_revisions_event_id_idx" ON "event_revisions"("event_id");
ALTER TABLE "event_revisions" ADD CONSTRAINT "event_revisions_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "event_revisions_actor_id_idx" ON "event_revisions"("actor_id");
ALTER TABLE "blocks" ADD CONSTRAINT "blocks_blocker_id_fkey" FOREIGN KEY ("blocker_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "blocks_blocker_id_idx" ON "blocks"("blocker_id");
ALTER TABLE "blocks" ADD CONSTRAINT "blocks_blocked_id_fkey" FOREIGN KEY ("blocked_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "blocks_blocked_id_idx" ON "blocks"("blocked_id");
ALTER TABLE "admin_sessions" ADD CONSTRAINT "admin_sessions_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "admin_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "admin_sessions_admin_id_idx" ON "admin_sessions"("admin_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_reporter_principal_id_fkey" FOREIGN KEY ("reporter_principal_id") REFERENCES "principals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_reporter_principal_id_idx" ON "reports"("reporter_principal_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_post_id_idx" ON "reports"("post_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_comment_id_idx" ON "reports"("comment_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_message_id_idx" ON "reports"("message_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_account_id_idx" ON "reports"("account_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_group_id_idx" ON "reports"("group_id");
ALTER TABLE "reports" ADD CONSTRAINT "reports_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "reports_event_id_idx" ON "reports"("event_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_report_id_idx" ON "moderation_actions"("report_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_admin_id_fkey" FOREIGN KEY ("admin_id") REFERENCES "admin_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_admin_id_idx" ON "moderation_actions"("admin_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_post_id_fkey" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_post_id_idx" ON "moderation_actions"("post_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_comment_id_idx" ON "moderation_actions"("comment_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "messages"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_message_id_idx" ON "moderation_actions"("message_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_account_id_idx" ON "moderation_actions"("account_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_group_id_idx" ON "moderation_actions"("group_id");
ALTER TABLE "moderation_actions" ADD CONSTRAINT "moderation_actions_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "moderation_actions_event_id_idx" ON "moderation_actions"("event_id");
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "notifications_account_id_idx" ON "notifications"("account_id");
ALTER TABLE "direct_contact_states" ADD CONSTRAINT "direct_contact_states_account_low_id_fkey" FOREIGN KEY ("account_low_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "direct_contact_states_account_low_id_idx" ON "direct_contact_states"("account_low_id");
ALTER TABLE "direct_contact_states" ADD CONSTRAINT "direct_contact_states_account_high_id_fkey" FOREIGN KEY ("account_high_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "direct_contact_states_account_high_id_idx" ON "direct_contact_states"("account_high_id");
ALTER TABLE "daily_usage" ADD CONSTRAINT "daily_usage_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "daily_usage_account_id_idx" ON "daily_usage"("account_id");
ALTER TABLE "group_owner_transfers" ADD CONSTRAINT "group_owner_transfers_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "group_owner_transfers_group_id_idx" ON "group_owner_transfers"("group_id");
ALTER TABLE "group_owner_transfers" ADD CONSTRAINT "group_owner_transfers_from_account_id_fkey" FOREIGN KEY ("from_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "group_owner_transfers_from_account_id_idx" ON "group_owner_transfers"("from_account_id");
ALTER TABLE "group_owner_transfers" ADD CONSTRAINT "group_owner_transfers_to_account_id_fkey" FOREIGN KEY ("to_account_id") REFERENCES "accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "group_owner_transfers_to_account_id_idx" ON "group_owner_transfers"("to_account_id");
ALTER TABLE "policy_configs" ADD CONSTRAINT "policy_configs_updated_by_admin_id_fkey" FOREIGN KEY ("updated_by_admin_id") REFERENCES "admin_accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "policy_configs_updated_by_admin_id_idx" ON "policy_configs"("updated_by_admin_id");

-- PostgreSQL 专用约束；不要只用 prisma db push（会遗漏本文件）。
CREATE UNIQUE INDEX principals_account_identity ON principals(account_id) WHERE kind='account';
CREATE UNIQUE INDEX group_single_owner ON group_members(group_id) WHERE role='owner' AND status='active';
CREATE UNIQUE INDEX membership_single_open_period ON membership_periods(group_member_id) WHERE end_sequence IS NULL;
CREATE UNIQUE INDEX group_single_pending_transfer ON group_owner_transfers(group_id) WHERE status='pending';
CREATE INDEX posts_public_feed ON posts(scope,status,published_at DESC,id DESC);
CREATE INDEX posts_region_feed ON posts(region_code,status,published_at DESC,id DESC);
CREATE INDEX comments_thread ON comments(post_id,status,published_at,id);
CREATE INDEX events_region_time ON events(status,region_code,starts_at,id);
CREATE INDEX notifications_account_time ON notifications(account_id,created_at DESC,id DESC);
CREATE INDEX outbox_ready ON outbox(status,available_at,id);
CREATE INDEX deletion_jobs_ready ON deletion_jobs(status,retry_after,id);
CREATE INDEX likes_reverse ON likes(to_account_id,from_account_id);
CREATE INDEX messages_expiry ON messages(expires_at,id);
CREATE INDEX posts_expiry ON posts(expires_at,id);
CREATE INDEX comments_expiry ON comments(expires_at,id);

-- UTC 日历年，2月29日自动夹到次年2月最后一天，不采用365天。
CREATE FUNCTION calendar_year_after(ts timestamptz) RETURNS timestamptz
LANGUAGE sql IMMUTABLE STRICT AS $$ SELECT ((ts AT TIME ZONE 'UTC') + INTERVAL '1 year') AT TIME ZONE 'UTC' $$;
CREATE FUNCTION content_retention() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='UPDATE' AND OLD.published_at IS NOT NULL THEN
  IF NEW.published_at IS DISTINCT FROM OLD.published_at THEN RAISE EXCEPTION 'published_at is immutable' USING ERRCODE='23514'; END IF;
 END IF;
 IF NEW.status='visible' AND NEW.published_at IS NULL THEN NEW.published_at=CURRENT_TIMESTAMP; END IF;
 NEW.expires_at=calendar_year_after(NEW.published_at);
 RETURN NEW;
END $$;
CREATE TRIGGER posts_retention BEFORE INSERT OR UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION content_retention();
CREATE TRIGGER comments_retention BEFORE INSERT OR UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION content_retention();
CREATE FUNCTION message_retention() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='UPDATE' AND NEW.sent_at IS DISTINCT FROM OLD.sent_at THEN RAISE EXCEPTION 'sent_at is immutable' USING ERRCODE='23514'; END IF;
 NEW.expires_at=calendar_year_after(NEW.sent_at); RETURN NEW;
END $$;
CREATE TRIGGER messages_retention BEFORE INSERT OR UPDATE ON messages FOR EACH ROW EXECUTE FUNCTION message_retention();
CREATE FUNCTION declaration_retention() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status='withdrawn' THEN NEW.expires_at=calendar_year_after(NEW.withdrawn_at); ELSE NEW.expires_at=NULL; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER declaration_retention BEFORE INSERT OR UPDATE ON age_declarations FOR EACH ROW EXECUTE FUNCTION declaration_retention();

CREATE FUNCTION comment_same_post() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.reply_to_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM comments WHERE id=NEW.reply_to_id AND post_id=NEW.post_id) THEN
  RAISE EXCEPTION 'reply must belong to same post' USING ERRCODE='23514';
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER comment_same_post BEFORE INSERT OR UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION comment_same_post();

-- 应用同事务创建group/owner/conversation，延迟到提交时核对；不在中间状态误报。
CREATE FUNCTION group_integrity() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE gid uuid; g groups%ROWTYPE; actual_count integer;
BEGIN
 IF TG_TABLE_NAME='groups' THEN gid=COALESCE(NEW.id,OLD.id); ELSE gid=COALESCE(NEW.group_id,OLD.group_id); END IF;
 SELECT * INTO g FROM groups WHERE id=gid FOR UPDATE;
 IF NOT FOUND THEN RETURN NULL; END IF;
 IF NOT EXISTS(SELECT 1 FROM group_members WHERE group_id=gid AND account_id=g.owner_id AND role='owner' AND status='active') THEN
  RAISE EXCEPTION 'group owner must have active owner membership' USING ERRCODE='23514';
 END IF;
 SELECT count(*) INTO actual_count FROM group_members WHERE group_id=gid AND status='active';
 IF g.active_count<>actual_count THEN RAISE EXCEPTION 'group active_count mismatch' USING ERRCODE='23514'; END IF;
 IF NOT EXISTS(SELECT 1 FROM conversations WHERE group_id=gid AND type='group') THEN RAISE EXCEPTION 'group requires conversation' USING ERRCODE='23514'; END IF;
 RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER group_integrity AFTER INSERT OR UPDATE ON groups DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION group_integrity();
CREATE CONSTRAINT TRIGGER member_integrity AFTER INSERT OR UPDATE OR DELETE ON group_members DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION group_integrity();
CREATE CONSTRAINT TRIGGER conversation_group_integrity AFTER INSERT OR UPDATE OR DELETE ON conversations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION group_integrity();

CREATE FUNCTION immutable_membership_identity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.group_id<>OLD.group_id OR NEW.account_id<>OLD.account_id THEN RAISE EXCEPTION 'membership identity is immutable' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER immutable_membership_identity BEFORE UPDATE ON group_members FOR EACH ROW EXECUTE FUNCTION immutable_membership_identity();

CREATE FUNCTION conversation_integrity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.type='dating' AND NOT EXISTS(SELECT 1 FROM matches WHERE id=NEW.match_id AND account_low_id=NEW.account_low_id AND account_high_id=NEW.account_high_id) THEN
  RAISE EXCEPTION 'dating pair differs from match' USING ERRCODE='23514';
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER conversation_integrity BEFORE INSERT OR UPDATE ON conversations FOR EACH ROW EXECUTE FUNCTION conversation_integrity();
CREATE FUNCTION participant_integrity() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM conversations WHERE id=NEW.conversation_id AND type IN ('direct','dating') AND NEW.account_id IN (account_low_id,account_high_id)) THEN
  RAISE EXCEPTION 'participant not in conversation pair' USING ERRCODE='23514';
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER participant_integrity BEFORE INSERT OR UPDATE ON conversation_participants FOR EACH ROW EXECUTE FUNCTION participant_integrity();

-- 单资源不得跨头像、帖子、回复、恋爱照片、活动封面复用；锁资源串行化绑定。
CREATE FUNCTION media_binding_integrity() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE mid uuid; binding_target text; asset media_assets%ROWTYPE; duplicates integer; expected_purpose text; principal uuid; account uuid;
BEGIN
 mid=(to_jsonb(NEW)->>TG_ARGV[0])::uuid; IF mid IS NULL THEN RETURN NEW; END IF;
 binding_target=to_jsonb(NEW)->>TG_ARGV[1]; expected_purpose=TG_ARGV[2];
 SELECT * INTO asset FROM media_assets WHERE id=mid FOR UPDATE;
 IF NOT FOUND THEN RETURN NEW; END IF; -- FK将在随后拒绝
 IF asset.purpose<>expected_purpose OR asset.status IN ('initiated','rejected','deleting','deleted') THEN
  RAISE EXCEPTION 'media purpose/status incompatible' USING ERRCODE='23514';
 END IF;
 IF TG_TABLE_NAME='post_media' THEN SELECT author_principal_id INTO principal FROM posts WHERE id=NEW.post_id;
 ELSIF TG_TABLE_NAME='comment_media' THEN SELECT author_principal_id INTO principal FROM comments WHERE id=NEW.comment_id;
 ELSIF TG_TABLE_NAME='profiles' THEN account=NEW.account_id;
 ELSIF TG_TABLE_NAME='dating_photos' THEN account=NEW.account_id;
 ELSIF TG_TABLE_NAME='events' THEN account=NEW.creator_id;
 END IF;
 IF principal IS NOT NULL THEN
  IF asset.owner_principal_id<>principal AND NOT EXISTS(SELECT 1 FROM principals a JOIN principals b ON a.account_id=b.account_id WHERE a.id=principal AND b.id=asset.owner_principal_id AND a.account_id IS NOT NULL) THEN
   RAISE EXCEPTION 'media owner mismatch' USING ERRCODE='23514'; END IF;
 ELSE
  IF NOT EXISTS(SELECT 1 FROM principals WHERE id=asset.owner_principal_id AND account_id=account) THEN RAISE EXCEPTION 'media owner mismatch' USING ERRCODE='23514'; END IF;
 END IF;
 SELECT count(*) INTO duplicates FROM (
  SELECT 'post_media' AS location,post_id::text AS target FROM post_media WHERE media_id=mid
  UNION ALL SELECT 'comment_media',comment_id::text FROM comment_media WHERE media_id=mid
  UNION ALL SELECT 'profiles',id::text FROM profiles WHERE avatar_media_id=mid
  UNION ALL SELECT 'dating_photos',account_id::text FROM dating_photos WHERE media_id=mid
  UNION ALL SELECT 'events',id::text FROM events WHERE cover_media_id=mid
 ) bindings WHERE NOT(location=TG_TABLE_NAME AND bindings.target=binding_target);
 IF duplicates>0 THEN RAISE EXCEPTION 'media already bound' USING ERRCODE='23514'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER post_media_binding BEFORE INSERT OR UPDATE ON post_media FOR EACH ROW EXECUTE FUNCTION media_binding_integrity('media_id','post_id','board');
CREATE TRIGGER comment_media_binding BEFORE INSERT OR UPDATE ON comment_media FOR EACH ROW EXECUTE FUNCTION media_binding_integrity('media_id','comment_id','board');
CREATE TRIGGER avatar_media_binding BEFORE INSERT OR UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION media_binding_integrity('avatar_media_id','id','profile');
CREATE TRIGGER dating_media_binding BEFORE INSERT OR UPDATE ON dating_photos FOR EACH ROW EXECUTE FUNCTION media_binding_integrity('media_id','account_id','dating');
CREATE TRIGGER event_media_binding BEFORE INSERT OR UPDATE ON events FOR EACH ROW EXECUTE FUNCTION media_binding_integrity('cover_media_id','id','event');

INSERT INTO policy_configs(key,value) VALUES
 ('ordinary_group_capacity','100'),('max_owned_ordinary_groups','5'),('daily_group_creations','2'),
 ('unanswered_direct_message_limit','3'),('daily_new_direct_targets','10'),('daily_timezone','"Asia/Tokyo"');
-- 频率、群拥有数、资格及read cursor必须由授权服务事务校验；schema不提供绕过身份的业务入口。

COMMIT;
