// 每条操作显式指定身份、请求和响应；G是游客或账号，不能误写成同时需要两种令牌。
const {ref,str,uuid,time,integer,bool,en,nullable,obj}=require('./schemas.cjs');
const operations=[];
const q=(name,schema,description,required=false)=>({name,in:'query',required,description,schema});
const page=[q('limit',{type:'integer',minimum:1,maximum:50,default:20},'每页20条，最大50。'),q('cursor',str('不透明游标。'),'筛选变化须重置游标。')];
const filters=[q('regionCode',str('地区代码。'),'只筛选公开大致地区。'),q('interestId',uuid(),'兴趣筛选。')];
function op(method,path,summary,auth,result,input,options={}){operations.push({method,path,summary,auth,result,input,...options});}
const list=(method,path,summary,auth,result,query=[])=>op(method,path,summary,auth,result,null,{list:true,query:[...page,...query]});
const deleted=(path,summary,auth,options={})=>op('delete',path,summary,auth,null,null,{status:204,...options});
op('post','/guest-sessions','创建本机游客凭证','P','GuestSession',null,{status:201,description:'浏览无需建立游客；发言前获取秘密凭证，仅本机管理自己的内容。'});
op('post','/auth/email-code','发送邮箱验证码','P','Challenge','EmailCodeInput',{status:202,decision:'邮箱验证码登录与六位代码格式仍为评审建议；注册邮箱已确认。'});
op('post','/auth/register','注册账号并可选接续游客内容','P','AuthSession','RegisterInput',{status:201,description:'guestToken仅证明接续；已注册邮箱不覆盖资料，验证后转登录结果。',alternate:200});
op('post','/auth/login','邮箱验证码登录','P','AuthSession','LoginInput',{decision:'邮箱验证码登录细节待确认。'});
op('post','/auth/refresh','轮换刷新令牌','P','AuthSession','RefreshInput',{description:'body中的刷新令牌是认证依据，非匿名开放；单次消费，重放撤销family。'});
op('post','/auth/logout','退出当前会话','U',null,null,{status:204});
op('post','/me/guest-claims','登录后接续游客内容','U','GuestClaim','GuestClaimInput',{idem:true});
op('get','/me','读取本人账号与设置','U','Me');
op('patch','/me/profile','更新普通资料','U','PublicProfile','ProfileInput',{version:true,description:'更新自己的资料，审核版本通过前不公开新内容。'});
op('patch','/me/settings','修改本人隐私与通知','U','Settings','SettingsInput');
op('get','/profiles/{accountId}','读取普通公开主页','P','PublicProfile',null,{optionalAuth:true,description:'不返回邮箱、游客主体、恋爱偏好或活动记录；canMessage由实际身份决定。'});
deleted('/me','申请注销账号','U',{input:'DeleteAccountInput',result:'JobAccepted',status:202,description:'验证码必须对应当前账号；立即撤销访问，清理由worker异步执行。'});
op('put','/me/push-devices/{installationId}','绑定当前推送安装','U','Settings','PushInput',{description:'token只写不回显，成功响应包含当前通知设置。'});
deleted('/me/push-devices/{installationId}','撤销本人安装推送','U');
op('get','/regions','查询地区字典','P','Region',null,{list:true,query:[q('parentCode',str('父地区代码。'),'筛选下一级地区。')],description:'字典版本通过响应ETag返回。'});
op('get','/interests','查询兴趣字典','P','Interest',null,{list:true});
list('get','/posts','浏览公开留言板','P','PublicPost',[...filters,q('q',str('中文关键词。'),'参数化关键词搜索。'),q('category',en('分类。','interest/city/general'),'分类筛选。'),q('sort',{type:'string',enum:['latest'],default:'latest'},'首稿按原始发布时间排序。')]);
op('get','/posts/{postId}','读取公开帖子','P','PublicPost',null,{description:'仅visible且未到期；本人待审从/me/content读取。'});
op('post','/posts','游客或账号发布图文帖子','G','ContentSubmit','PostInput',{status:201,idem:true});
op('patch','/posts/{postId}','本人重提待审或拒绝帖子','G','ContentSubmit','PostInput',{version:true,owner:true,decision:'已公开帖子不直接编辑仍为建议规则。'});
deleted('/posts/{postId}','删除本人帖子','G',{owner:true,description:'立即不可见，不连带删除未到期回复正文。'});
list('get','/posts/{postId}/comments','浏览公开回复','P','Reply');
op('post','/posts/{postId}/comments','游客或账号图文回复','G','ContentSubmit','ReplyInput',{status:201,idem:true});
op('patch','/comments/{commentId}','重提本人回复','G','ContentSubmit','ReplyInput',{version:true,owner:true});
deleted('/comments/{commentId}','删除本人回复','G',{owner:true});
list('get','/me/content','读取本主体发布与回复','G','OwnContent',[q('kind',en('类别。','posts/comments'),'选择自己的内容类别。',true)]);
op('get','/me/content/{kind}/{contentId}','读取本人内容或过期占位','G','OwnContent',null,{owner:true});
op('get','/discovery/interests/{interestId}','读取兴趣主题讨论与群','P',obj('讨论与群的游标独立。',{interest:ref('Interest'),posts:{$ref:'#/components/schemas/PublicPostPage'},groups:{$ref:'#/components/schemas/GroupPage'}}),null,{query:[...filters.filter(x=>x.name!=='interestId'),q('postsCursor',str('帖子游标。'),'帖子独立分页。'),q('groupsCursor',str('群游标。'),'群独立分页。')]});
op('post','/media/upload-intents','申请受控上传签名','G','UploadIntent','UploadInput',{status:201,idem:true,description:'dating用途另要求登录和self_declared。'});
op('post','/media/{mediaId}/complete','完成上传并受理审核','G','Media','CompleteUploadInput',{status:202,idem:true,owner:true});
op('get','/media/{mediaId}','读取本人资源状态','G','Media',null,{owner:true});
op('get','/media/{mediaId}/access','获取有权访问的展示图','P','MediaAccess',null,{optionalAuth:true,query:[q('variant',{type:'string',enum:['display','thumbnail'],default:'display'},'展示图或缩略图。')],description:'仅已审核且所属内容有权访问；公开图片可匿名，恋爱/私有必须对应资格，无权统一404。'});
deleted('/media/{mediaId}','删除本人未关联资源','G',{owner:true,description:'已关联资源需修改/删除父对象，禁止破坏其他对象绑定。'});
list('get','/groups','浏览普通公开群概要','P','Group',filters);
op('get','/groups/{groupId}','读取群概要','P','Group',null,{optionalAuth:true,description:'普通群公开，活动/恋爱类型须对应资格，无权404。'});
op('post','/groups','注册用户创建普通群','U','GroupCreated','GroupInput',{status:201,idem:true,description:'普通群100人含群主；最多拥有5个未解散普通群，东京每日最多创建2个。'});
op('patch','/groups/{groupId}','群主修改群资料','U','Group','GroupPatchInput',{version:true,owner:true});
op('post','/groups/{groupId}/join','注册用户直接加入普通群','U','GroupJoin',null,{idem:true,description:'无需审批；受控类型必须按来源资格加入，容量与封禁后台检查。'});
deleted('/groups/{groupId}/membership','退出当前群','U',{description:'群主先完成自愿转让，独自一人可解散。'});
list('get','/groups/{groupId}/members','读取有权群成员','U','Member');
op('patch','/groups/{groupId}/membership','修改本人群免打扰','U','Member','MutedInput');
deleted('/groups/{groupId}/members/{accountId}','群主移除并封禁成员','U',{input:'ReasonInput',owner:true});
op('post','/groups/{groupId}/owner-transfer','向指定成员发起群主转让','U','Transfer','TargetInput',{status:201,idem:true,owner:true});
op('post','/groups/{groupId}/owner-transfers/{transferId}/accept','指定接任者自愿接受','U','Transfer','AcceptTransferInput',{idem:true,description:'仅指定接任者本人，未接受不改变owner；检查目标拥有群配额。'});
op('post','/groups/{groupId}/close','二次确认解散普通群','U','GroupClosed','CloseGroupInput',{idem:true,owner:true,description:'停止加入/发送，原成员在原读取范围内只读，记录仍按原发送一年删除。'});
list('get','/me/groups','读取本人有效群','U','MyGroup');
op('post','/direct-conversations','建立独立普通私聊','U','Conversation','DirectInput',{status:201,alternate:200,idem:true,description:'不要求年龄声明/匹配；对方回复前最多3条、每天新联系10人。关闭陌生接收仍保留已有成功联系，空会话不能绕过。'});
list('get','/conversations','读取本人有权会话','U','Conversation',[q('type',en('类型。','group/direct/dating'),'区分普通与恋爱会话。')]);
op('get','/conversations/{conversationId}/messages','读取授权消息并断线补取','U','Message',null,{list:true,messagePage:true,query:[page[0],q('afterSequence',str('非负序号。',{pattern:'^(0|[1-9][0-9]*)$'}),'与beforeSequence互斥。'),q('beforeSequence',str('非负序号。',{pattern:'^(0|[1-9][0-9]*)$'}),'与afterSequence互斥。')],description:'过滤到期/拉黑/权限空洞后仍推进scannedThroughSequence；群只读当前加入区间；dating还需有效匹配和资格。'});
op('post','/conversations/{conversationId}/messages','持久化发送文字消息','U','Message','MessageInput',{status:201,alternate:200,description:'以clientMessageId去重，不依赖额外Idempotency-Key；提交后ACK，与WS调用同一服务。'});
op('put','/conversations/{conversationId}/read-cursor','推进本人已读位置','U','ReadCursor','ReadInput');
op('patch','/conversations/{conversationId}/settings','修改本人会话设置','U','ConversationSettings','ConversationSettingsInput');
op('post','/dating/age-declarations','主动声明已满18岁','U','AgeDeclaration','AgeInput',{idem:true});
deleted('/dating/age-declarations','撤销年龄声明与恋爱权限','U');
op('get','/me/dating-profile','读取本人的恋爱编辑资料','U','DatingProfile',null,{description:'本人编辑设置可读，尚无资料时404；不授予他人发现资格。'});
op('put','/me/dating-profile','保存独立恋爱资料','U','DatingProfile','DatingInput',{version:true,description:'需要self_declared；首次创建使用If-Match "0"，工程约定；返回版本从1起。',decision:'偏好字段待确认，首稿仅接受空preferences对象。'});
op('patch','/me/dating-profile/enabled','主动开关恋爱展示','U','DatingProfile','EnabledInput',{description:'关闭不要求恋爱资格；开启须有效声明和合格资料。'});
list('get','/dating/candidates','读取受控恋爱候选','D','DatingProfile',filters);
op('get','/dating/profiles/{accountId}','读取受控恋爱详情','D','DatingProfile');
op('post','/dating/likes','喜欢或跳过候选','D','LikeResult','LikeInput',{idem:true});
list('get','/dating/matches','读取本人有效匹配','D','Match');
deleted('/dating/matches/{matchId}','结束本人匹配及恋爱通信','D',{owner:true});
list('get','/events','浏览公开同城活动','P','EventPublic',[...filters,q('from',time(),'时间范围开始。'),q('to',time(),'时间范围结束。')]);
op('get','/events/{eventId}','读取活动公开详情','P','EventPublic');
op('post','/events','注册用户发布活动或保存草稿','U','EventSubmission','EventInput',{status:201,idem:true,description:'无需组织者预授权；私有集合字段不进入公开DTO。'});
op('patch','/events/{eventId}','发布者修改本人活动','U','EventSubmission','EventPatchInput',{version:true,owner:true,description:'已有报名后改时间/集合/取消规则须confirmChanges=true并通知具体变更；人数不得低于当前报名。'});
op('post','/events/{eventId}/cancel','开始前确认取消活动','U','EventSubmission','ReasonInput',{version:true,idem:true,owner:true,description:'原因必填，停止报名，通知报名者，群转只读；开始后改走end。'});
op('post','/events/{eventId}/end','开始后提前结束活动','U','EventSubmission','EndEventInput',{version:true,idem:true,owner:true});
op('get','/events/{eventId}/private-details','读取授权集合信息','U',obj('不能进入公开DTO/通知/锁屏。',{meetingInstructions:str('私有集合信息。'),version:integer('版本。',1)}),null,{description:'仅发布者/有效报名者，取消报名或退出者立即失去资格。'});
op('post','/events/{eventId}/registrations','按当前规则报名','U','RegistrationResult','RegistrationInput',{status:201,alternate:200,idem:true,description:'版本冲突412，最后名额竞争需原子事务，发布者不占报名名额。',errors:[412]});
deleted('/events/{eventId}/registrations/me','取消报名或退出活动','U',{description:'开始前取消释放名额；开始后left退出不释放，均撤销本人群访问。'});
list('get','/events/{eventId}/registrations','发布者读取报名名单','U','Registration');operations.at(-1).owner=true;
list('get','/me/events','读取本人参与或创建活动','U','MyEvent',[q('role',en('角色。','participant/creator'),'自己的记录类别。',true),q('status',en('状态。','draft/pending/open/ended/cancelled/hidden'),'活动状态。')]);
list('get','/notifications','读取本人通知','U','Notification');
op('put','/notifications/{notificationId}/read','标记本人通知已读','U',obj('本人通知阅读结果。',{readAt:time()}),null,{owner:true});
op('post','/reports','游客或账号举报有权内容','G','Report','ReportInput',{status:201,idem:true});
list('get','/me/reports','读取本人举报反馈','G','Report');
op('post','/blocks','屏蔽注册账号','U','PublicProfile','TargetInput',{idem:true,description:'禁止自屏蔽；响应只含目标普通公开资料，双向阻止私聊。'});
list('get','/blocks','读取本人屏蔽名单','U','PublicProfile');
deleted('/blocks/{accountId}','解除本人屏蔽','U');
op('post','/admin/auth/login','独立管理员凭证登录','P','AdminChallenge','AdminLoginInput');
op('post','/admin/auth/mfa','完成管理员MFA','P','AdminSession','AdminMfaInput',{description:'挑战本身是认证证明，不接受手机用户令牌；成功才获得管理会话。'});
list('get','/admin/reports','审核角色读取举报队列','A','AdminReport',[q('status',en('状态。','open/reviewing/resolved'),'队列筛选。')]);
op('get','/admin/reports/{reportId}','审核角色读取必要举报上下文','A','AdminReport');
list('get','/admin/content','审核角色读取待审内容','A','AdminContent',[q('status',en('状态。','pending/rejected'),'队列状态。',true),q('targetType',en('目标。','post/comment/profile/dating/event'),'对象类别。')]);
op('post','/admin/moderation-actions','管理员处理单个对象','A','AuditAction','ModerationInput',{status:201,idem:true,description:'需要对应操作角色；reason和expectedVersion验证，auditor不得写入。'});
list('get','/admin/groups','运营角色管理群概要','A','Group');
list('get','/admin/events','运营角色管理活动概要','A','EventPublic');
list('get','/admin/accounts','运营角色管理账号概要','A','AdminAccount');
list('get','/admin/tasks','运维角色读取任务状态','A','Task');
op('post','/admin/tasks/{taskId}/retry','运维角色重试失败任务','A','Task',null,{status:202,idem:true,description:'只重试失败任务，成功任务不能重执行；操作者须有对应运维授权。'});
list('get','/admin/audit-actions','审计角色读取操作记录','A','AuditAction',[q('from',time(),'开始。'),q('to',time(),'结束。')]);
module.exports={operations};
