// DTO按公开/本人/恋爱/后台隔离；不直接导出数据库实体或秘密字段。
const ref=name=>({$ref:`#/components/schemas/${name}`});
const str=(description,extra={})=>({type:'string',description,...extra});
const uuid=()=>str('UUID对象标识；知道ID不代表有权访问。',{format:'uuid'});
const time=()=>str('带时区的ISO8601时间，响应统一使用UTC/Z。',{format:'date-time'});
const integer=(description,min=0)=>({type:'integer',minimum:min,description});
const bool=description=>({type:'boolean',description});
const en=(description,values)=>str(description,{enum:values.split('/')});
const nullable=s=>({anyOf:[s,{type:'null'}],description:'可为空；空值不表示当前已授权或已发布。'});
const arr=(items,max)=>({type:'array',items,uniqueItems:true,...(max!==undefined?{maxItems:max}:{})});
const obj=(description,properties,required=Object.keys(properties))=>({type:'object',description,properties,required,additionalProperties:false});
// Unicode可见字符不是JSON Schema的码点长度：扩展规则由共享校验器和测试执行。
const text=(description,max,nonempty=false)=>str(description,{...(max?{'x-grapheme-max':max}:{}),...(nonempty?{minLength:1,pattern:'\\S'}:{})});
const seq=()=>str('非负十进制bigint字符串，不能转成JS Number。',{pattern:'^(0|[1-9][0-9]*)$'});
const schemas={};
const add=(name,s)=>{schemas[name]=s;return ref(name);};
const ids=(max)=>({...arr(uuid(),max),default:[]});
add('Region',obj('标准地区字典。',{code:str('标准地区代码。'),parentCode:nullable(str('父级地区代码。')),level:en('地区层级。','prefecture/municipality'),nameJa:str('日文名称。'),nameZh:str('中文名称。')}));
add('Interest',obj('兴趣字典。',{id:uuid(),code:str('稳定兴趣代码。'),nameZh:str('中文名称。')}));
add('Capabilities',obj('仅指导界面，服务端每次操作仍重新鉴权。',{canRead:bool('可读取。'),canSend:bool('可发消息。'),canEdit:bool('可编辑。'),canDelete:bool('可删除。'),canJoin:bool('可加入。'),canMessage:bool('可普通私聊。')},[]));
add('Image',obj('受控展示图片，不暴露存储对象键。',{id:uuid(),url:str('短时受控展示URL，不能长于内容剩余寿命。',{format:'uri'}),width:integer('展示宽度。',1),height:integer('展示高度。',1),expiresAt:time()}));
add('AuthorDisplay',{description:'游客只显示同帖标签；注册作者只返回普通公开资料。',oneOf:[obj('游客标签。',{kind:{const:'guest',type:'string'},label:str('同帖稳定显示标签。')}),obj('注册作者。',{kind:{const:'account',type:'string'},accountId:uuid(),nickname:str('公开昵称。'),avatar:nullable(ref('Image'))})]});
add('PublicProfile',obj('普通公开资料，无邮箱、游客主体、恋爱偏好或活动记录。',{id:uuid(),nickname:str('公开昵称。'),bio:str('公开简介。'),avatar:nullable(ref('Image')),region:nullable(ref('Region')),interests:arr(ref('Interest')),capabilities:ref('Capabilities')}));
add('Settings',obj('陌生私聊默认开放；关闭不影响已有成功联系，拉黑仍禁止双方通信。',{allowStrangerDm:{...bool('允许新陌生人私聊。'),default:true},pushEnabled:bool('允许推送，默认值仍为工程建议。'),lockscreenPreview:bool('显示锁屏预览，建议默认false。')}));
add('AgeDeclaration',obj('自我声明而非证件核验。',{status:en('声明状态，无verified。','not_declared/self_declared/withdrawn'),declaredAt:nullable(time()),withdrawnAt:nullable(time())}));
add('Me',obj('仅本人可读的账号与资料。',{id:uuid(),email:str('本人邮箱，禁止进入公开DTO。',{format:'email'}),status:en('账号状态。','active/restricted/deleting/deleted'),profile:nullable(ref('PublicProfile')),settings:ref('Settings'),ageDeclaration:ref('AgeDeclaration'),onboardingRequired:bool('是否需要完善基本资料。')}));
add('GuestSession',obj('首次发言建立的本机秘密凭证，禁止写入URL或日志。',{guestToken:str('高熵游客秘密凭证。'),principalId:uuid()}));
add('AuthSession',obj('仅登录/注册成功返回的令牌；禁止缓存到公开请求或记录日志。',{accessToken:str('短期账号令牌。'),refreshToken:str('可轮换刷新令牌。'),account:ref('Me'),onboardingRequired:bool('是否需要基本资料。'),claimStatus:en('游客接续不成功不应丢失登录结果。','not_requested/claimed/failed')}));
add('Challenge',obj('统一响应，不泄漏邮箱是否注册。',{challengeId:uuid(),expiresIn:integer('有效秒数。',1),retryAfter:integer('最短等待秒数。')}));
const published={publishedAt:time(),expiresAt:time()};
const submit={id:uuid(),status:en('公开与待审必须区分。','pending/visible/rejected/hidden/deleted/expired'),publishedAt:nullable(time()),expiresAt:nullable(time()),version:integer('资源版本。',1)};
add('ContentSubmit',obj('提交状态，pending不代表公开成功。',submit));
const post={id:uuid(),title:str('公开标题。'),body:str('纯文本正文。'),authorDisplay:ref('AuthorDisplay'),region:nullable(ref('Region')),interests:arr(ref('Interest')),images:arr(ref('Image'),9),replyCount:integer('可见未过期回复数。'),...published,capabilities:ref('Capabilities')};
add('PublicPost',obj('仅可见未到期的公开帖子，无稳定游客ID。',post));
add('Reply',obj('回复独立计时，引用过期内容只给无正文占位。',{id:uuid(),postId:uuid(),body:str('纯文本回复。'),authorDisplay:ref('AuthorDisplay'),images:arr(ref('Image'),3),replyToId:nullable(uuid()),...published,capabilities:ref('Capabilities')}));
add('OwnContent',{description:'本人待审/公开内容或无正文的过期占位。',oneOf:[obj('本人有效内容。',{kind:en('内容类别。','posts/comments'),...submit,title:str('仅帖子有标题。'),body:str('本人正文。'),images:arr(ref('Image'),9),parentUnavailable:bool('父帖是否已不可用。')},['kind','id','status','body','images','version']),obj('已删除或过期占位，无标题/正文/作者/图片。',{kind:en('内容类别。','posts/comments'),id:uuid(),status:en('终态。','deleted/expired'),unavailable:{type:'boolean',const:true}})]});
add('Media',obj('本主体资源状态，不返回objectKey。',{id:uuid(),status:en('资源状态。','initiated/uploaded/processing/approved/rejected/deleting/deleted'),purpose:en('用途隔离。','board/profile/dating/event'),sizeBytes:integer('实际字节数。',1)}));
add('UploadIntent',obj('上传签名与公开URL不同，先上传再完成与审核。',{mediaId:uuid(),uploadUrl:str('临时受控上传URL。',{format:'uri'}),uploadHeaders:{type:'object',description:'上传时需原样附带的头部。',additionalProperties:{type:'string'}},expiresAt:time()}));
add('MediaAccess',obj('按所属内容重新鉴权的图片访问。',{url:str('受控短时URL。',{format:'uri'}),expiresAt:time()}));
add('Group',obj('公开群概要，不包含聊天正文或成员名单。',{id:uuid(),name:str('群名。'),description:str('群介绍。'),rules:str('群规。'),type:en('群类型。','ordinary/event/dating'),status:en('解散为readonly，closed不授予历史读取。','active/readonly/closed'),capacity:nullable(integer('普通群默认100，含群主。',1)),activeCount:integer('有效成员数。'),region:nullable(ref('Region')),interest:nullable(ref('Interest')),version:integer('版本。',1),dissolvedAt:nullable(time()),capabilities:ref('Capabilities')}));
add('Member',obj('成员公开资料与当前资格。',{account:ref('PublicProfile'),role:en('群角色。','owner/member'),status:en('成员状态，不存在pending审批。','active/left/banned'),muted:bool('本人成员设置。')}));
add('GroupJoin',obj('已成功加入，无审批阶段。',{membership:ref('Member'),conversationId:uuid()}));
add('GroupCreated',obj('创建者成为群主，同事务创建会话。',{group:ref('Group'),conversationId:uuid(),role:{type:'string',const:'owner'}}));
add('MyGroup',obj('本人的群摘要。',{group:ref('Group'),role:en('角色。','owner/member'),unreadCount:integer('有权未过期未读消息数。'),conversationId:uuid()}));
add('Conversation',obj('会话摘要，普通私聊不携带恋爱状态。',{id:uuid(),type:en('互相独立的会话类型。','group/direct/dating'),status:en('读写状态。','active/readonly/closed'),participants:arr(ref('PublicProfile'),2),lastSequence:seq(),unreadCount:integer('实际可见未读数，不直接用序号差。'),capabilities:ref('Capabilities')}));
add('Message',obj('仅有权且未过期消息；响应序号为字符串。',{id:uuid(),conversationId:uuid(),senderDisplay:ref('PublicProfile'),clientMessageId:uuid(),sequence:seq(),body:str('纯文本消息。'),sentAt:time(),expiresAt:time(),status:{type:'string',const:'visible'}}));
add('ReadCursor',obj('已读高水位。',{lastReadSequence:seq()}));
add('ConversationSettings',obj('个人会话偏好，不修改群状态。',{muted:bool('免打扰。'),archived:bool('是否归档。')}));
add('Transfer',obj('接任者未同意前不改变群主。',{transferRequestId:uuid(),status:en('转让状态。','pending/accepted/cancelled')}));
add('GroupClosed',obj('群解散结果，原成员保持原范围只读。',{id:uuid(),status:{type:'string',const:'readonly'},dissolvedAt:time()}));
add('DatingPreferences',obj('偏好字段未评审，首稿只接受空对象，后续扩展不能接受任意敏感字段。',{}));
add('DatingProfile',obj('受控恋爱资料，禁止公开缓存与普通私聊入口。',{accountId:uuid(),intro:str('恋爱简介。'),region:nullable(ref('Region')),interests:arr(ref('Interest')),photos:arr(ref('Image'),6),preferences:ref('DatingPreferences'),enabled:bool('主动展示意愿。'),status:en('资料审核状态。','pending/visible/rejected/hidden'),version:integer('版本。',1)}));
add('LikeResult',obj('不暴露对方跳过行为。',{matched:bool('是否匹配。'),matchId:nullable(uuid()),conversationId:nullable(uuid())}));
add('Match',obj('本人有效匹配。',{id:uuid(),profile:ref('DatingProfile'),conversationId:uuid(),matchedAt:time()}));
const event={id:uuid(),title:str('标题。'),description:str('公开说明。'),cover:nullable(ref('Image')),region:ref('Region'),interests:arr(ref('Interest')),startsAt:time(),endsAt:time(),registrationDeadline:time(),capacity:integer('报名名额，不含发布者。',1),confirmedCount:integer('开始后退出不释放历史名额。'),status:en('活动状态。','draft/pending/open/ended/cancelled/hidden'),cancellationPolicy:str('取消规则。'),version:integer('活动版本。',1),capabilities:ref('Capabilities')};
add('EventPublic',obj('公开活动，不含私有集合说明或报名名单。',event));
add('EventSubmission',obj('活动草稿、待审或操作结果。',{id:uuid(),status:event.status,version:integer('版本。',1),cancelledAt:nullable(time()),actualEndedAt:nullable(time())},['id','status','version']));
add('Registration',obj('报名资格，开始前取消与开始后退出分开。',{id:uuid(),eventId:uuid(),account:ref('PublicProfile'),status:en('报名状态。','confirmed/cancelled/left'),acceptedEventVersion:integer('接受规则版本。',1),registeredAt:time()}));
add('RegistrationResult',obj('报名与活动群资格同事务成功。',{registration:ref('Registration'),conversationId:uuid()}));
add('MyEvent',obj('仅本人的参与记录。',{event:ref('EventPublic'),role:en('本人角色。','participant/creator'),registration:nullable(ref('Registration'))}));
add('Notification',obj('通知不复制私有正文，跳转目标重新鉴权。',{id:uuid(),type:str('通知类型。'),targetType:str('跳转对象类型。'),targetId:uuid(),readAt:nullable(time()),createdAt:time()}));
add('Report',obj('本人举报反馈，不暴露审核员或其他举报者。',{id:uuid(),status:en('举报处理状态。','open/reviewing/resolved'),createdAt:time()}));
add('AdminReport',obj('管理角色必要的举报元信息；上下文按对象独立授权。',{report:ref('Report'),targetType:en('目标。','post/comment/message/account/group/event'),targetId:uuid(),reasonCode:str('举报理由代码。'),detail:str('必要说明。')}));
add('AdminAccount',obj('管理账号概要，不返回凭证/令牌/MFA秘密。',{id:uuid(),status:en('用户状态。','active/restricted/deleting/deleted'),profile:nullable(ref('PublicProfile'))}));
add('AdminContent',obj('待审内容版本，仅角色有权读取。',{targetType:en('审核对象类型。','post/comment/profile/dating/event'),targetId:uuid(),status:en('审核状态。','pending/rejected'),version:integer('版本。',1),title:str('适用对象的标题。'),body:str('允许范围的正文。'),images:arr(ref('Image'),9)},['targetType','targetId','status','version']));
add('Task',obj('任务管理概要，不暴露敏感payload。',{id:uuid(),type:str('任务类型。'),status:en('任务状态。','pending/processing/succeeded/dead/completed/failed'),attempts:integer('重试次数。'),lastErrorCode:nullable(str('脱敏错误代码。'))}));
add('AuditAction',obj('必要审计，不复制正文。',{id:uuid(),adminId:uuid(),targetType:str('对象类型。'),targetId:uuid(),action:str('操作类型。'),reason:str('操作理由。'),createdAt:time()}));
add('Error',obj('统一失败格式，不泄漏内部异常或拉黑关系。',{code:str('稳定业务错误码。'),message:str('中文可读说明。'),requestId:str('脱敏请求追踪ID。'),details:arr(obj('字段错误。',{field:str('字段路径。'),reason:str('错误理由。'),limit:integer('适用限额。')},['field','reason']))},['code','message','requestId']));
add('JobAccepted',obj('异步受理，不代表清理已完成。',{deletionJobId:uuid()}));
add('GuestClaim',obj('游客接续结果，不公开关联历史身份。',{claimedContentCounts:obj('接续数量。',{posts:integer('帖子数。'),comments:integer('回复数。')})}));
// 请求只允许明确列出的字段，禁止客户端写author/owner/verified/status。
add('EmailCodeInput',obj('申请验证码，参数仍为可调整工程配置。',{email:str('邮箱。',{format:'email'}),purpose:en('用途。','login/register/delete_account')}));
const challengeInput={challengeId:uuid(),code:str('邮箱验证码。',{pattern:'^[0-9]{6}$','x-decision-status':'工程初值：六位格式待登录细节确认'}),guestToken:str('可选原游客秘密，证明接续所有权。')};
add('RegisterInput',obj('注册接受指定条款版本，可选游客接续。',{...challengeInput,termsVersion:str('条款版本。',{minLength:1}),privacyVersion:str('隐私政策版本。',{minLength:1})},['challengeId','code','termsVersion','privacyVersion']));
add('LoginInput',obj('邮箱验证码登录仍为评审建议。',challengeInput,['challengeId','code']));
add('DeleteAccountInput',obj('本账号邮箱对应删除挑战。',{challengeId:uuid(),code:challengeInput.code}));
add('RefreshInput',obj('单次轮换刷新令牌。',{refreshToken:str('原刷新秘密令牌。',{minLength:1})}));
add('GuestClaimInput',obj('额外游客证明不能按邮箱自动认领。',{guestToken:str('原游客秘密凭证。',{minLength:1})}));
add('ProfileInput',obj('部分更新普通资料；昵称与简介限额仍为建议，不固化未确认数值。',{nickname:text('昵称。',null,true),bio:text('简介。'),regionCode:nullable(str('地区代码。')),interestIds:ids(),avatarMediaId:nullable(uuid())},[]));schemas.ProfileInput.minProperties=1;
add('SettingsInput',obj('仅可更新本人设置。',schemas.Settings.properties,[]));schemas.SettingsInput.minProperties=1;
add('PushInput',obj('当前安装推送绑定。',{token:str('推送令牌，禁止日志回显。',{minLength:1}),platform:en('平台。','ios/android')}));
const postInput={title:text('最多60个可见字符。',60,true),body:text('最多2000个可见字符。',2000,true),category:en('普通公开分类。','interest/city/general'),regionCode:nullable(str('地区代码。')),interestIds:ids(),mediaIds:ids(9)};
add('PostInput',obj('普通公开发帖，scope由服务端确定。',postInput,['title','body','category']));
const reply=obj('文字或图片至少有一种；正文最多1000个可见字符。',{body:text('回复正文。',1000),replyToId:nullable(uuid()),mediaIds:ids(3)},[]);reply.anyOf=[{required:['body'],properties:{body:{type:'string',pattern:'\\S'}}},{required:['mediaIds'],properties:{mediaIds:{type:'array',minItems:1}}}];add('ReplyInput',reply);
add('UploadInput',obj('申请静态图片签名，服务端仍核对实际格式与大小。',{purpose:en('恋爱用途须有效年龄声明。','board/profile/dating/event'),fileName:str('可选文件名，不作为对象键。'),mime:en('仅静态图片，动图解码拒绝。','image/jpeg/image/png/image/webp'),sizeBytes:{...integer('5MB=5,000,000 bytes。',1),maximum:5000000}},['purpose','mime','sizeBytes']));schemas.UploadInput.properties.mime.enum=['image/jpeg','image/png','image/webp'];
add('CompleteUploadInput',obj('完成上传检查，可不提供checksum。',{checksum:str('可选内容校验摘要。')},[]));
const groupInput={name:text('群名最多30个可见字符。',30,true),description:text('群介绍最多1000。',1000),rules:text('群规限额另行评审。'),regionCode:nullable(str('地区代码。')),interestId:uuid()};
add('GroupInput',obj('创建普通群，不能指定owner/type/capacity。',groupInput,['name','description','interestId']));
add('GroupPatchInput',obj('群主部分更新，不能直接指定转让目标或群状态。',groupInput,[]));schemas.GroupPatchInput.minProperties=1;
add('MutedInput',obj('本人免打扰设置。',{muted:bool('是否免打扰。')}));
add('ReasonInput',obj('原因必填，长度政策另行评审。',{reason:text('操作原因。',null,true)}));
add('TargetInput',obj('指定注册目标，服务端检查访问来源与角色。',{targetAccountId:uuid()}));
add('AcceptTransferInput',obj('只有指定接任者本人接受才提交转让。',{accepted:{type:'boolean',const:true,description:'明确自愿接任。'}}));
add('CloseGroupInput',obj('二次确认解散群。',{confirmed:{type:'boolean',const:true,description:'已确认只读解散。'},reason:text('可选说明。')},['confirmed']));
const direct=obj('普通私聊无年龄或匹配条件，首次联系限额服务端执行。',{targetAccountId:uuid(),source:en('只能普通公开资料或共同有效群。','publicProfile/groupMember'),sourceGroupId:uuid()},['targetAccountId','source']);direct.allOf=[{if:{properties:{source:{const:'groupMember'}},required:['source']},then:{required:['sourceGroupId']},else:{not:{required:['sourceGroupId']}}}];add('DirectInput',direct);
add('MessageInput',obj('仅文字聊天；重试保持同ID，资格、3条首次及每日10人由事务检查。',{clientMessageId:{...uuid(),pattern:'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-7[0-9a-fA-F]{3}-[89aAbB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$',description:'UUIDv7；建议30天离线和未来5分钟窗口在服务端验证。'},body:text('最多1000可见字符，不能为空。',1000,true)}));
add('ReadInput',obj('单调递增且不超过有权高水位。',{lastReadSequence:seq()}));
add('ConversationSettingsInput',obj('部分更新本人会话设置。',{muted:bool('免打扰。'),archived:bool('归档。')},[]));schemas.ConversationSettingsInput.minProperties=1;
add('AgeInput',obj('复选框不可预选，不产生verified。',{accepted:{type:'boolean',const:true,description:'本人主动声明已满18岁。'},statementVersion:str('声明文案版本。',{minLength:1})}));
add('DatingInput',obj('恋爱编辑独立于公开资料，年龄声明有效后可准备。',{intro:text('简介字段及限额仍需评审。'),regionCode:nullable(str('地区代码。')),interestIds:ids(),photoMediaIds:ids(6),preferences:ref('DatingPreferences')},['intro','interestIds','photoMediaIds','preferences']));
add('EnabledInput',obj('关闭不要求恋爱资格，开启要求声明与合格资料。',{enabled:bool('是否主动开启恋爱意愿。')}));
add('LikeInput',obj('喜欢或跳过，不暴露对方跳过。',{targetAccountId:uuid(),decision:en('决定。','like/skip')}));
const eventInput={title:text('活动标题最多60。',60,true),description:text('活动说明最多3000。',3000,true),regionCode:str('有效地区代码。',{minLength:1}),interestIds:ids(),startsAt:time(),endsAt:time(),registrationDeadline:time(),capacity:integer('人数>0，减少不得低于已有报名。',1),cancellationPolicy:text('取消规则。',null,true),meetingInstructions:text('仅报名者可见集合说明。',null,true),coverMediaId:nullable(uuid()),saveAsDraft:{...bool('保存为草稿。'),default:false}};
add('EventInput',obj('注册用户发布；截止≤开始<结束须服务端跨字段校验。',eventInput,['title','description','regionCode','startsAt','endsAt','registrationDeadline','capacity','cancellationPolicy','meetingInstructions']));
add('EventPatchInput',obj('重要修改需confirmChanges，不能PATCH状态；已开始不通过改开始时间恢复取消资格。',{...eventInput,changeReason:text('变更说明。'),confirmChanges:bool('已确认向报名者说明具体变更。')},[]));schemas.EventPatchInput.minProperties=1;
add('EndEventInput',obj('开始后提前结束，保留记录与群只读。',{confirmed:{type:'boolean',const:true,description:'本人确认提前结束。'},reason:text('提前结束原因。',null,true)}));
add('RegistrationInput',obj('确认当前规则版本，报名与群资格同事务。',{acceptedEventVersion:integer('当前活动版本。',1),acceptedRules:{type:'boolean',const:true,description:'已阅读并接受规则。'}}));
const targetType=en('举报目标类型。','post/comment/message/account/group/event');
add('ReportInput',obj('需有权读取目标，匿名游客不能举报私有会话。',{targetType,targetId:uuid(),reasonCode:str('社区规则中的理由代码，运营规则另评审。',{minLength:1}),detail:text('可选补充。')},['targetType','targetId','reasonCode']));
add('AdminLoginInput',obj('独立管理登录，不接受用户令牌。',{loginName:str('管理员登录名。',{minLength:1}),password:str('秘密凭证，禁止日志。',{minLength:1})}));
add('AdminMfaInput',obj('管理MFA挑战，不是手机用户验证码。',{challengeId:uuid(),code:str('MFA验证码。',{pattern:'^[0-9]{6}$'})}));
add('AdminChallenge',obj('管理MFA挑战。',{challengeId:uuid(),expiresAt:time()}));
add('AdminSession',obj('独立管理令牌，与用户audience分离。',{accessToken:str('管理访问秘密。'),expiresAt:time(),role:en('角色。','reviewer/operator/auditor')}));
add('ModerationInput',obj('平台处理单个目标，理由和旧版本均需验证。',{targetType,targetId:uuid(),action:en('操作集合需运营确认，首稿建议。','approve/reject/hide/delete/restrict/unrestrict'),reason:text('必填处理依据。',null,true),expectedVersion:integer('资源当前版本。',1)}));
module.exports={schemas,ref,str,uuid,time,integer,bool,en,nullable,arr,obj};
