const fs=require('node:fs'),path=require('node:path');
const {tables}=require('./model.cjs');
// 注释由规范源输出，避免手改迁移后被下一次生成覆盖。
const {tableComments,columnComments}=require('./comments.cjs');
const root=path.resolve(__dirname,'..');
const types={uuid:['uuid','String',' @db.Uuid'],text:['text','String',''],time:['timestamptz','DateTime',' @db.Timestamptz(6)'],date:['date','DateTime',' @db.Date'],int:['integer','Int',''],bigint:['bigint','BigInt',''],bool:['boolean','Boolean',''],json:['jsonb','Json','']};
const model=n=>n.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join('');
for(const t of tables){t.columns=t.fields.split(' ').map(s=>{const [name,info]=s.split(':');const [type,ref]=info.split('@');return {name,type:type.replace('?',''),nullable:type.includes('?'),ref};});if(t.common!==false)t.columns.unshift({name:'id',type:'uuid'},{name:'created_at',type:'time'},{name:'updated_at',type:'time'});t.pk??=['id'];t.defaults={...(t.common!==false?{id:'gen_random_uuid()',created_at:'CURRENT_TIMESTAMP',updated_at:'CURRENT_TIMESTAMP'}:{}),...t.defaults};t.relations=[];t.back=[];}
let sql='-- 初始数据库迁移：由tools/generate.cjs生成，说明来源为comments.cjs。\n-- 修改model.cjs、comments.cjs或constraints.sql后重新生成；已部署迁移须另建增量版本。\n-- 本文件只建立结构及默认配置，业务权限、频率扣额和物理删除仍需API/worker。\n-- 全部变更在同一事务提交，任一步失败不留下半套表结构。\nBEGIN;\n';
let prisma='// Generated model: PostgreSQL CHECK/partial indexes/triggers are in migration.sql.\ngenerator client {\n  provider = "prisma-client-js"\n  output = "../generated/client"\n}\ndatasource db {\n  provider = "postgresql"\n  url = env("DATABASE_URL")\n}\n';
// 主键、唯一性和状态检查就近说明；只增加SQL行注释，不改变结构语句。
for(const t of tables){if(!tableComments[t.name])throw Error('Missing Chinese table comment: '+t.name);const cols=t.columns.map(c=>`${columnComments[c.name]?'  -- '+columnComments[c.name]+'\n':''}  "${c.name}" ${types[c.type][0]}${c.nullable?'':' NOT NULL'}${t.defaults[c.name]!==undefined?' DEFAULT '+t.defaults[c.name]:''}`);cols.push(`  -- 主键：唯一定位记录；连接表使用组合键避免重复关系。\n  PRIMARY KEY (${t.pk.map(n=>`"${n}"`).join(',')})`);for(const u of t.unique)cols.push(`  -- 唯一组合 ${u}：拒绝重复绑定或重复业务记录。\n  UNIQUE (${u.split(',').map(n=>`"${n}"`).join(',')})`);t.checks.forEach((c,i)=>cols.push(`  -- 检查约束：限制允许状态、合法字段组合或数值边界。\n  CONSTRAINT "${t.name}_check_${i}" CHECK (${c})`));sql+=`\n-- ${tableComments[t.name]}\nCREATE TABLE "${t.name}" (\n${cols.join(',\n')}\n);\n`;}
sql+='\n-- 外键及关联索引：RESTRICT防止绕过资源清理；索引支持关联查询及引用检查。\n';
for(const t of tables)for(const c of t.columns.filter(c=>c.ref)){const [table,key='id']=c.ref.split('.');const target=tables.find(t=>t.name===table);if(!target)throw Error('Missing FK target '+table);const name=`${t.name}_${c.name}_fkey`;sql+=`ALTER TABLE "${t.name}" ADD CONSTRAINT "${name}" FOREIGN KEY ("${c.name}") REFERENCES "${table}"("${key}") ON DELETE RESTRICT ON UPDATE CASCADE;\n`;sql+=`CREATE INDEX "${t.name}_${c.name}_idx" ON "${t.name}"("${c.name}");\n`;const unique=t.unique.includes(c.name)||t.pk.length===1&&t.pk[0]===c.name;t.relations.push(`  rel_${c.name} ${model(table)}${c.nullable?'?':''} @relation("${name}", fields: [${c.name}], references: [${key}], onDelete: Restrict, onUpdate: Cascade)`);target.back.push(`  back_${t.name}_${c.name} ${model(t.name)}${unique?'?':'[]'} @relation("${name}")`);}
for(const t of tables){const fields=t.columns.map(c=>{let f=`  ${c.name} ${types[c.type][1]}${c.nullable?'?':''}${types[c.type][2]}`;if(t.pk.length===1&&t.pk[0]===c.name)f+=' @id';const d=t.defaults[c.name];if(d!==undefined){const v=d==='CURRENT_TIMESTAMP'?'now()':d==='gen_random_uuid()'?'dbgenerated("gen_random_uuid()")':d.startsWith("'")&&d.endsWith("'")?JSON.stringify(d.slice(1,-1)):d==="'{}'::jsonb"?'"{}"':d;f+=` @default(${v})`;}return f;});if(t.pk.length>1)fields.push(`  @@id([${t.pk.join(', ')}])`);for(const u of t.unique)fields.push(`  @@unique([${u.split(',').join(', ')}])`);prisma+=`\nmodel ${model(t.name)} {\n${[...fields,...t.relations,...t.back,`  @@map("${t.name}")`].join('\n')}\n}\n`;}
sql+='\n'+fs.readFileSync(path.join(root,'sql/constraints.sql'),'utf8')+'\nCOMMIT;\n';
const files={'prisma/schema.prisma':prisma,'prisma/migrations/202610030001_initial/migration.sql':sql,'prisma/migrations/migration_lock.toml':'provider = "postgresql"\n'};
for(const [file,content] of Object.entries(files)){const p=path.join(root,file);if(process.argv.includes('--check')){if(!fs.existsSync(p)||fs.readFileSync(p,'utf8')!==content)throw Error('Generated file differs: '+file);}else{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,content);}}
console.log(`${tables.length} models: ${process.argv.includes('--check')?'generated files match':'generated Prisma schema and SQL migration'}`);
